SAVEPOINT before_username_delete;
BEGIN;
	REVOKE ALL ON SCHEMA <schema> FROM USERNAME;
	REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA <schema> FROM USERNAME;
	REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA <schema> FROM USERNAME;
	REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA <schema> FROM USERNAME;
	ALTER DEFAULT PRIVILEGES IN SCHEMA <schema> REVOKE ALL ON TABLES FROM USERNAME;
	ALTER DEFAULT PRIVILEGES IN SCHEMA <schema> REVOKE ALL ON SEQUENCES FROM USERNAME;
	ALTER DEFAULT PRIVILEGES IN SCHEMA <schema> REVOKE ALL ON FUNCTIONS FROM USERNAME;

	REASSIGN OWNED BY USERNAME TO OTHER_USER;
	DROP USER IF EXISTS USERNAME;
COMMIT;
-- ROLLBACK TO SAVEPOINT before_username_delete;